name: 'Comenta os resultados do benchmark'
description: 'teste de action'
# Aqui nos definimos as entradas, quais serão setadas do arquivo do workflow e que será consumida pelo nosso codigo
inputs:
  json_file:
    description: 'Aonde encontramos o arquivo json do benchmark'
    required: true
    default: 'output.json'
  comparison_json_file:
    description: 'Aonde encontramos o arquivo json para comparar os benchmarks'
    required: false
    default: ''
  token:
    description: 'GitHub token'
    default: $
    required: true
# Aqui nos especificamos o arquivoi index.js como ponto de entrada
runs:
  using: 'node12'
  main: 'dist/index.js'