# Workflow para pull request
name: Benchmark para pull requests e comparação
on:
  pull_request:
    branches:
      - "main"

jobs:
  benchmark:
    runs-on: ubuntu-latest
    name: Roda os testes e compara
    steps:
      - name: Checkout
        uses: actions/checkout@v2

        # Exemplo de como baixar os artefatos de outras branchs de outros repositorios do github
      - name: Baixa os artefatos gerados pelos testes
        uses: dawidd6/action-download-artifact@v2
        with:
          # O ${ }é como o github interpola as variaveis
          github_token: $
          # Referencia para outro arquivo de workflow
          workflow: benchmark_default.yml
          # O nome dos artefatos criados la
          name: benchmark_results
          # Aonde colocar os artefatos baixados
          path: old_benchmark
          commit: $
        continue-on-error: true
      - name: Compara e comenta
        # Usar a ação definida nesse repositorio 
        uses: ./
        with:
          # Nos passamos dois argumentos
          # Caminho do json
          json_file: "benchmark.json"
          # Caminho do arquivo json que será comparado
          comparison_json_file: "old_benchmark/benchmark.json"