# Workflow que executa os testes do script e exporta os resultados como artefatos
name: Benchmark para a banch principal
# Roda somente em novos commits na branch principal
on:
  push:
    branches:
      - "main" # Branch padrão

# Jobs
jobs:
  benchmark:
    runs-on: ubuntu-latest
    name: Rodar testes
    steps:
        # Cada passo pode ter a referencia de outros repositorios go github como é o caso, 
        # observe que todas as referencias preciam ter as tags representando suas versões
        # A primeira tarefa, apenas clona seu repositorio dentro da area de trabalho do workflow
      - name: Checkout
        uses: actions/checkout@v2

        # Envia os resultados como artefatos
      - name: Upload dos artefatos
        uses: actions/upload-artifact@v2
        # Argumentos passados para o actions
        with:
          name: benchmark_results
          path: benchmark.json

  checa-resultados:
    runs-on: ubuntu-latest
    name: Checa resultados
    steps:
      - name: Checkout
        run: echo "check dos resultados"
    needs: benchmark

